import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";

export default function Home() {
  const user = useUser();

  return (
    <>
      <Head>
        <title>DM's Companion</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen justify-center items-center">
        { !user.isSignedIn && <SignInButton /> }
        { !!user.isSignedIn && <SignOutButton /> }
      </div>
    </>
  );
}
