import { useUser } from "@clerk/nextjs";
import {type  NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "~/components/navigation";
import { api, RouterOutputs } from "~/utils/api";

const CreateCampaignWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex gap-3 w-full">
      <Image 
        src={user.profileImageUrl} 
        className="rounded-full" 
        width={56}
        height={56}
        alt={`${user.username}`} />
      <input 
        placeholder="Campaign Title"
        className="bg-transparent grow outline-none"
      />
    </div>
   )
}

type CampaignWithUser = RouterOutputs["campaigns"]["getAll"][number]
const CampaignView = (props: CampaignWithUser) => {
  const { campaign, author } = props;

  return (
    <div key={campaign.id} className="flex flex-row p-4 gap-3">
      <Image 
        src={author.profileImageUrl} 
        className="rounded-full" 
        width={56}
        height={56}
        alt={`${author.username}`} 
      />
      <div className="flex flex-col">
        <div className="flex">
          <span>{author.name}</span>
        </div>
        <span>{campaign.title}</span>
      </div>
    </div>
  )
}

const Home: NextPage = () => {
  const user = useUser();
  const { data, isLoading } = api.campaigns.getAll.useQuery()

  if (isLoading) return <div>Loading...</div>
  if (!data) return <div>Something went wrong.</div>

  return (
    <>
      <Head>
        <title>DMs Companion</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="h-screen">
        { user.isSignedIn && <CreateCampaignWizard /> }
        <div>
          { data.map((fullCampaignData) => (
            <CampaignView {...fullCampaignData} key={fullCampaignData.campaign.id} />
          ))}
        </div>
      </div>
    </>
  );
}

export default Home