import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();

  const { data } = api.campaigns.getAll.useQuery()

  return (
    <>
      <Head>
        <title>DMs Companion</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen justify-center items-center flex-col">
        { !user.isSignedIn && <SignInButton /> }
        { !!user.isSignedIn && <SignOutButton /> }
        <div>
          { data?.map((campaign) => (<div key={campaign.id}>{campaign.title}</div>))}
        </div>
      </div>
    </>
  );
}
